### ISSUE TITLE
Add here

### ISSUE THREAD

**Issue by wang3303** [AGKhalil/Cellphone_Robot#9]
https://github.com/AGKhalil/Cellphone_Robot/blob/ddf4c589e4e3df823717e14bde4deca23517812a/app/src/main/java/com/example/khalil/myrobot/NaturalLanguageProcessService.kt#L210

**Comment by wang3303** [comment]
```
// this is for removing the quotation mark
if (platform != "") {
            platform = platform.substring(1, shape.length - 1)
            Log.d(TAG, shape + "!!!")
        }
if platfom == this phone or platform == ""
            execute the command on this phone
elseif platform == the other phone
            forward this message to the other phone.
```

**Comment by wang3303** [comment]
Remember to initiate `var platform = ""`

**Comment by AGKhalil** [comment]
Michael,  is "platform" equal to the sender's phone number? If so, why do we need to specify that? As long as the phone I am texting knows which phone to text, we should be ok. I want to text Lily or Mickey or any future robots to text said number xxx-xxx-xxx. Let me know if Im misinterpreting anything.
